/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./**/*.html",
    "./**/*.js",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'bg-dark': 'var(--bg-dark)',
        'bg-darker': 'var(--bg-darker)',
        'bg-cyan': 'var(--bg-cyan)',
        'bg-overlay': 'var(--bg-overlay)',
        'bg-card': 'var(--bg-card)',
        'bg-hover': 'var(--bg-hover)',
        'text-white': 'var(--text-white)',
        'text-gray-200': 'var(--text-gray-200)',
        'text-gray-300': 'var(--text-gray-300)',
        'text-gray-500': 'var(--text-gray-500)',
        'text-gray-600': 'var(--text-gray-600)',
        'text-gray-700': 'var(--text-gray-700)',
        'text-gray-800': 'var(--text-gray-800)',
        'text-gray-900': 'var(--text-gray-900)',
        'text-gray-950': 'var(--text-gray-950)',
        'text-cyan-400': 'var(--text-cyan-400)',
        'text-cyan-500': 'var(--text-cyan-500)',
        'text-cyan-600': 'var(--text-cyan-600)',
        'text-cyan-700': 'var(--text-cyan-700)',
        'text-cyan-800': 'var(--text-cyan-800)',
        'text-cyan-900': 'var(--text-cyan-900)',
        'text-cyan-950': 'var(--text-cyan-950)',
        'text-yellow-500': 'var(--text-yellow-500)',
        'border-cyan-500': 'var(--border-cyan-500)',
        'border-gray-300': 'var(--border-gray-300)',
        'fill-gray-950': 'var(--fill-gray-950)',
        'cor-azul': 'var(--cor-azul)',
        'cor-preto': 'var(--cor-preto)',
      },
    },
  },
  plugins: [],
}
